// mypages.js
// 2023-03-01

exports.genMainPage = function (date) {
    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <title></title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>TPC3</h1>
                </header>
                <div class="w3-container w3-center">
                    <p><a href="#">Lista de Pessoas</a></p>
                    <p><a href="#">Distribuição por sexo</a></p>
                    <p><a href="#">Distribuição por desporto</a></p>
                    <p><a href="#">Top 10 de profissões</a></p>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Emanuel Silva: ${date}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.genPessoasPage = function (lista, date) {
    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <title></title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                            <th>Profissão</th>
                            <th>Desportos</th>
                        </tr>`
    for (let i = 0; i < lista.length; i++) 
    {
        pagHTML += 
        `
            <tr>
                <td>${lista[i].id}</td>
                <td><a href="http://localhost:5555/pessoas/${lista[i].id}">${lista[i].nome}</a></td>
                <td>${lista[i].idade}</td>
                <td>${lista[i].sexo}</td>
                <td>${lista[i].morada.cidade}</td>
                <td>${lista[i].profissao}</td>
                <td>${lista[i].desportos}</td>
            </tr>
        `
    }

    pagHTML += `
                    </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Pessoas-Server: ${date}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.genPessoaPage = function (pessoa, date) {
    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <title></title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>${pessoa.nome}</h1>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                            <th>Profissão</th>
                            <th>Desportos</th>
                        </tr>`
        pagHTML += 
        `
            <tr>
                <a href="http://localhost:5555/pessoas/${pessoa.id}">
                    <td>${pessoa.id}</td>
                    <td>${pessoa.nome}</td>
                    <td>${pessoa.idade}</td>
                    <td>${pessoa.sexo}</td>
                    <td>${pessoa.morada.cidade}</td>
                    <td>${pessoa.profissao}</td>
                    <td>${pessoa.desportos}</td>
                </a>
            </tr>
        `

    pagHTML += `
                    </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Pessoas-Server: ${date}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}