// mypages.js
// 2023-03-01

exports.genMainPage = function (date) 
{
    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <title></title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>TPC3</h1>
                </header>
                <div class="w3-container w3-center">
                    <p><a href="http://localhost:5555/pessoas">Lista de Pessoas</a></p>
                    <p><a href="http://localhost:5555/distSexo">Distribuição por sexo</a></p>
                    <p><a href="http://localhost:5555/distDesporto">Distribuição por desporto</a></p>
                    <p><a href="http://localhost:5555/topProfissoes">Top 10 de profissões</a></p>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Pessoas-Server: ${date}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.genPessoasPage = function (lista, date) 
{
    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <title></title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                            <th>Profissão</th>
                            <th>Desportos</th>
                        </tr>`
    for (let i = 0; i < lista.length; i++) 
    {
        pagHTML += 
        `
            <tr>
                <td>${lista[i].id}</td>
                <td><a href="http://localhost:5555/pessoas/${lista[i].id}">${lista[i].nome}</a></td>
                <td>${lista[i].idade}</td>
                <td>${lista[i].sexo}</td>
                <td>${lista[i].morada.cidade}</td>
                <td>${lista[i].profissao}</td>
                <td>${lista[i].desportos}</td>
            </tr>
        `
    }

    pagHTML += `
                    </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Pessoas-Server: ${date}</h5>
                    <h4><a href="http://localhost:5555/">Voltar ao Menu</a><h4>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.genPessoaPage = function (pessoa, date) 
{
    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <title></title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1>${pessoa.nome}</h1>
                </header>
                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                            <th>Profissão</th>
                            <th>Desportos</th>
                        </tr>`
        pagHTML += 
        `
            <tr>
                <a href="http://localhost:5555/pessoas/${pessoa.id}">
                    <td>${pessoa.id}</td>
                    <td>${pessoa.nome}</td>
                    <td>${pessoa.idade}</td>
                    <td>${pessoa.sexo}</td>
                    <td>${pessoa.morada.cidade}</td>
                    <td>${pessoa.profissao}</td>
                    <td>${pessoa.desportos}</td>
                </a>
            </tr>
        `

    pagHTML += 
    `
                    </table>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by Pessoas-Server: ${date}</h5>
                    <h4><a href="http://localhost:5555/">Voltar ao Menu</a><h4>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.distSexoPage = function (lista, date) 
{
    const dist = new Map()
    let total = lista.length
    
    lista.forEach((pessoa) => {
        if(!dist.has(pessoa.sexo)) dist.set(pessoa.sexo, 0)
        let n = dist.get(pessoa.sexo)
        dist.set(pessoa.sexo,++n)
    })

    for (const [key, value] of dist.entries()) dist.set(key,(value/total)*100)

    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8"/>
            <title>Sex Distribution</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4 w3-center">
            <header class="w3-blue">
              <h1>Distribuição de pessoas por sexo</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-large">
                <tr>
                  <th>Sexo</th>
                  <th>%</th>
                </tr>`

        for (const [key, value] of dist.entries()) 
        {
            pagHTML+= `<tr>
                    <td><a href="http://localhost:5555/sexo/${key}">${key}</a></td>
                    <td>${value.toFixed(4)}</td>
                    </tr>`
        }

        pagHTML+= `
                </table>
            </div>
            <footer class="w3-container w3-blue w3-center">
              <h5>Generated by pessoas-server: ${date}</h5>
              <h4><a href="http://localhost:5555/">Voltar ao Menu</a><h4>
            </footer>
            </div>

        </body>
    </html>
    `

    return pagHTML
}

exports.distDesportoPage = function (lista, date) 
{
    const dist = new Map()
    let total = lista.length
    
    lista.forEach((pessoa) => {
        let desportos = pessoa.desportos
        desportos.forEach((d) => {
            if(!dist.has(d)){
                dist.set(d, 0)
            }
            let n = dist.get(d)
            dist.set(d,++n)
        })
        
    })

    for (const [key, value] of dist.entries()) dist.set(key,(value/total)*100)

    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8"/>
            <title>About people</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4 w3-center">
            <header class="w3-container w3-blue">
              <h1>Distribuição de pessoas por desporto</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-large">
                <tr>
                  <th>Desporto</th>
                  <th>%</th>
                </tr>`

        for (const [key, value] of dist.entries()) 
        {
            let encoded = encodeURIComponent(key)
            pagHTML+= `<tr>
                    <td><a href="http://localhost:5555/desporto/${encoded}">${key}</a></td>
                    <td>${value.toFixed(4)}</td>
                    </tr>`
        }

        pagHTML+= 
        `
                </table>
            </div>
            <footer class="w3-container w3-blue w3-center">
              <h5>Generated by pessoas-server: ${date}</h5>
              <h4><a href="http://localhost:5555/">Voltar ao Menu</a><h4>
            </footer>
            </div>

        </body>
    </html>
    `    
    return pagHTML
}

exports.topProfPage = function (lista, date) 
{
    dist = new Map()
    
    lista.forEach((pessoa) => {
        if(!dist.has(pessoa.profissao)){
            dist.set(pessoa.profissao, 0)
        }
        let n = dist.get(pessoa.profissao)
        dist.set(pessoa.profissao,++n)
    })


    const mapSort = new Map([...dist.entries()].sort((a, b) => b[1] - a[1]));

    const top10 = Array.from(mapSort).slice(0,10)
    
    var pagHTML = 
    `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8"/>
            <title>About people</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body class="w3-container">
            <div class="w3-card-4 w3-center">
            <header class="w3-container w3-blue">
              <h1>Top 10 Profissões</h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all w3-hoverable w3-large">
                <tr>
                  <th>Profissão</th>
                  <th>Quantidade de pessoas</th>
                </tr>`

        for (let i = 0 ; i < top10.length ; i++) 
        {
            let encoded = encodeURIComponent(top10[i][0])
            pagHTML+= `<tr>
                    <td><a href="http://localhost:5555/profissoes/${encoded}">${top10[i][0]}</a></td>
                    <td>${top10[i][1]}</td>
                    </tr>`
        }

        pagHTML+= `
                </table>
            </div>
            <footer class="w3-container w3-blue w3-center">
              <h5>Generated by pessoas-server: ${date}</h5>
              <h4><a href="http://localhost:5555/">Voltar ao Menu</a><h4>
            </footer>
            </div>

        </body>
    </html>
    `    

    return pagHTML
}