exports.mainPage = function(tasks, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>TPC4</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h1 class="w3-center">Tasks List (TPC4)</h1>
                </header>
                <div class="w3-cell-row">
                    <form action="/tasks/registo" class="w3-container w3-cell" method="POST">
                        <h1>Tasks Form</h1>
                        <fieldset>
                            <label class="w3-text-grey">Task Name</lable>
                            <input class="w3-input w3-border" type="text" required>
                            <label class="w3-text-grey">Due Date</lable>
                            <input class="w3-input w3-border" type="text" required>
                            <label class="w3-text-grey">Who</lable>
                            <input class="w3-input w3-border" type="text" required>
                            <label class="w3-text-grey">What</lable>
                            <input class="w3-input w3-border" type="text" required>
                            <button class="w3-button w3-green w3-round w3-right w3-margin-top" type="submit">Register</button>
                        </fieldset>
                    </form>
                    <form action="/users/registo" class="w3-container w3-cell" method="POST">
                        <h1>Users Form</h1>
                        <fieldset>
                            <label class="w3-text-grey">Name</lable>
                            <input class="w3-input w3-border" type="text" required>
                            <label class="w3-text-grey">Email</lable>
                            <input class="w3-input w3-border" type="text" required>
                            <button class="w3-button w3-green w3-round w3-right w3-margin-top" type="submit">Register</button>
                        </fieldset>
                    </form>
                </div>
                <div class="w3-cell-row">
                    <div class="w3-container w3-cell" style="width:50%">
                        <h1>Tasks To Do</h1>
                            <table class="w3-table-all">
                                <tr>
                                    <th>Id</th><th>Name</th><th>Due Date</th><th>Who</th><th>What</th>
                                    <th>Actions</th>
                                </tr>
                `
                
    for(let i=0; i < tasks.length ; i++){
        if (!("done" in tasks[i]))
        pagHTML += `
                <tr>
                    <td>${tasks[i].id}</td>
                    <td>
                        <a href="/tasks/${tasks[i].id}">
                            ${tasks[i].nome}
                        </a>
                    </td>
                    <td>${tasks[i].duedate}</td>
                    <td>${tasks[i].who}</td>
                    <td>${tasks[i].what}</td>
                    <td>
                        [<a href="/tasks/edit/${tasks[i].id}">Edit</a>][<a href="/tasks/done/${tasks[i].id}">Done</a>][<a href="/tasks/delete/${tasks[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }
        pagHTML += `
                </table>
            </div>

            <div class="w3-container w3-cell" style="width:50%">
                <h1>Tasks Completed</h1>
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Due Date</th><th>Who</th><th>What</th><th>Actions</th>
                        </tr>
        `
                
    for(let i=0; i < tasks.length ; i++){
        if (("done" in tasks[i]))
        pagHTML += `
                <tr>
                    <td>${tasks[i].id}</td>
                    <td>
                        <a href="/tasks/${tasks[i].id}">
                            ${tasks[i].nome}
                        </a>
                    </td>
                    <td>${tasks[i].duedate}</td>
                    <td>${tasks[i].who}</td>
                    <td>${tasks[i].what}</td>
                    <td>
                        [<a href="/tasks/delete/${tasks[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
                    </table>
                </div>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by TPC4 server in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.taskFormPage = function(t,d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h2>Task Page</h2>
                </header>
            
                <div class="w3-container" method="POST">
                    <fieldset>
                        <label>Id</label>    
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${t.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" readonly value="${t.nome}"/>
                        <label>Due Date</label>
                        <input class="w3-input w3-round" type="text" name="duedate" readonly value="${t.duedate}"/>
                        <label>Who</label>
                        <input class="w3-input w3-round" type="text" name="who" readonly value="${t.who}"/>
                        <label>What</label>
                        <input class="w3-input w3-round" type="text" name="what" readonly value="${t.what}"/>
                        `
                        if ("done" in t)
                        {
                            pagHTML += `
                            <label>Done</label>
                            <input class="w3-input w3-round" type="text" name="done"  value="${t.done}"/>
                            `
                        }
                        
                        pagHTML += `
                        </div>
                        </fieldset>

                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.taskFormEditPage = function(t, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-blue">
                    <h2>Task Edit Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${t.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"  value="${t.nome}"/>
                        <label>Due Date</label>
                        <input class="w3-input w3-round" type="text" name="duedate"  value="${t.duedate}"/>
                        <label>Who</label>
                        <input class="w3-input w3-round" type="text" name="who"  value="${t.who}"/>
                        <label>What</label>
                        <input class="w3-input w3-round" type="text" name="what"  value="${t.what}"/>
                        `
                        if ("done" in t)
                        {
                            pagHTML += `
                                <label>Done</label>
                                <input class="w3-input w3-round" type="text" name="done"  value="${t.done}"/>
                                `
                        }

            pagHTML += `
                        <button class="w3-btn w3-green w3-mb-2 w3-margin-top" type="submit">Register</button>
                        </fieldset> 
                </form>

                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}
